; Based on cmarkit.ml
; - Refactored into smaller modules
; - Expose internal via cmarkit_.ml module
; - Public interface is kept in cmarkit.ml and constrained by the original cmarkit.mli file
; - Contains additional modules: Inline_parse, Pp, Sexp_

(library
 (name cmarkit_)
 (public_name oymarkit.internal)
 (libraries cmarkit_data cmarkit_base)
 (modules
  cmarkit_
  common_
  attribute
  inline
  block
  doc
  parser_common_
  inline_struct
  parser
  inline_parse_api
  pp
  sexp
  struct_)
 (inline_tests)
 (preprocess
  (pps ppx_jane ppx_expect)))

(library
 (name cmarkit)
 (public_name oymarkit.cmarkit)
 (libraries cmarkit_ cmarkit_data cmarkit_base)
 (modules cmarkit)
 (inline_tests)
 (preprocess
  (pps ppx_jane ppx_expect)))
