(tests
  (names test_parser_config test_inline_struct)
  (libraries cmarkit_ cmarkit_commonmark cmarkit_html fmt)
  (modules test_parser_config test_inline_struct)
  (preprocess (pps ppx_sexp_conv))
)

(library
  (name test_jsx)
  (libraries cmarkit_ cmarkit_commonmark cmarkit_html cmarkit_latex)
  (modules test_jsx)
  (inline_tests)
  (preprocess (pps ppx_expect))
)

(library
  (name test_span)
  (libraries cmarkit_ cmarkit_commonmark cmarkit_html)
  (modules test_span)
  (inline_tests)
  (preprocess (pps ppx_expect))
)

(library
  (name test_thematic_break)
  (libraries cmarkit_ cmarkit_commonmark cmarkit_html)
  (modules test_thematic_break)
  (inline_tests)
  (preprocess (pps ppx_expect))
)

(library
  (name test_smart_punct)
  (libraries cmarkit_ cmarkit_commonmark cmarkit_html cmarkit_latex)
  (modules test_smart_punct)
  (inline_tests)
  (preprocess (pps ppx_expect))
)

(library
  (name test_symbol)
  (libraries cmarkit_ cmarkit_commonmark cmarkit_html sexplib0)
  (modules test_symbol)
  (inline_tests)
  (preprocess (pps ppx_expect ppx_sexp_conv))
)