(library
 (name omarkit)
 (wrapped false)
 (modules
  cmarkit
  cmarkit_commonmark
  cmarkit_html
  cmarkit_latex
  cmarkit_renderer)
 (libraries cmarkit_data cmarkit_base qcheck)
 (preprocess
  (pps ppx_jane ppx_deriving_qcheck)))

(library
 (name cmarkit_data)
 (modules cmarkit_data cmarkit_data_uchar cmarkit_data_html))
