(library
 (name cmarkit_data)
 (modules cmarkit_data cmarkit_data_uchar cmarkit_data_html))

(library
 (name cmarkit_renderer)
 (modules cmarkit_renderer)
 (libraries oymarkit))

(library
 (name cmarkit_html)
 (modules cmarkit_html)
 (libraries oymarkit cmarkit_renderer))

(library
 (name cmarkit_commonmark)
 (modules cmarkit_commonmark)
 (libraries oymarkit cmarkit_renderer))

(library
 (name cmarkit_latex)
 (modules cmarkit_latex)
 (libraries oymarkit cmarkit_renderer))
